services:
  - type: web
    name: scheduler-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: DATABASE_TYPE
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
      - key: ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app

databases:
  - name: scheduler-db
    databaseName: scheduler_db
    plan: free
